files:
  - source: Metro/localisation/english/**/**.yml
    ignore:
      - Metro/localisation/english/VDN
      - Metro/localisation/english/ULI
      - Metro/localisation/english/TRT
      - Metro/localisation/english/TECH
      - Metro/localisation/english/STG
      - Metro/localisation/english/SPT
      - Metro/localisation/english/SEV
      - Metro/localisation/english/SCA
    translation: Metro/localisation/%language%/%original_file_name%.yml
