files:
  - source: Metro/localisation/english/ALK/**
    translation: Metro/localisation/%language%/ALK/%original_file_name%
  - source: Metro/localisation/english/ARB
    translation: Metro/localisation/%language%/ARB/%original_file_name%
  - source: Metro/localisation/english/AVT
    translation: Metro/localisation/%language%/AVT/%original_file_name%
  - source: Metro/localisation/english/BAU
    translation: Metro/localisation/%language%/BAU/%original_file_name%
  - source: Metro/localisation/english/BRK
    translation: Metro/localisation/%language%/BRK/%original_file_name%
  - source: Metro/localisation/english/DIM
    translation: Metro/localisation/%language%/DIM/%original_file_name%
  - source: Metro/localisation/english/EUR
    translation: Metro/localisation/%language%/EUR/%original_file_name%
  - source: Metro/localisation/english/GWC
    translation: Metro/localisation/%language%/GWC/%original_file_name%
  - source: Metro/localisation/english/HNZ/**
    translation: Metro/localisation/%language%/HNZ/%original_file_name%
  - source: Metro/localisation/english/HUL
    translation: Metro/localisation/%language%/HUL/%original_file_name%
  - source: Metro/localisation/english/ISL
    translation: Metro/localisation/%language%/ISL/%original_file_name%
  - source: Metro/localisation/english/KAL
    translation: Metro/localisation/%language%/KAL/%original_file_name%
  - source: Metro/localisation/english/KTG
    translation: Metro/localisation/%language%/KTG/%original_file_name%
  - source: Metro/localisation/english/KUZ
    translation: Metro/localisation/%language%/KUZ/%original_file_name%
  - source: Metro/localisation/english/MSU
    translation: Metro/localisation/%language%/MSU/%original_file_name%
  - source: Metro/localisation/english/MUT
    translation: Metro/localisation/%language%/MUT/%original_file_name%
  - source: Metro/localisation/english/PEC
    translation: Metro/localisation/%language%/PEC/%original_file_name%
  - source: Metro/localisation/english/PVL
    translation: Metro/localisation/%language%/PVL/%original_file_name%
  - source: Metro/localisation/english/RANDOM_EVENTS
    translation: Metro/localisation/%language%/RANDOM_EVENTS/%original_file_name%
  - source: Metro/localisation/english/RCH
    translation: Metro/localisation/%language%/RCH/%original_file_name%
  - source: Metro/localisation/english/RED
    translation: Metro/localisation/%language%/RED/%original_file_name%
  - source: Metro/localisation/english/RMJ
    translation: Metro/localisation/%language%/RMJ/%original_file_name%
  - source: Metro/localisation/english/RYZ
    translation: Metro/localisation/%language%/RYZ/%original_file_name%
  - source: Metro/localisation/english/SAT
    translation: Metro/localisation/%language%/SAT/%original_file_name%
  - source: Metro/localisation/english/SCA
    translation: Metro/localisation/%language%/SCA/%original_file_name%
  - source: Metro/localisation/english/SEV
    translation: Metro/localisation/%language%/SEV/%original_file_name%
  - source: Metro/localisation/english/SPT
    translation: Metro/localisation/%language%/SPT/%original_file_name%
  - source: Metro/localisation/english/STG
    translation: Metro/localisation/%language%/STG/%original_file_name%
  - source: Metro/localisation/english/TECH
    translation: Metro/localisation/%language%/TECH/%original_file_name%
  - source: Metro/localisation/english/TRT
    translation: Metro/localisation/%language%/TRT/%original_file_name%
  - source: Metro/localisation/english/ULI
    translation: Metro/localisation/%language%/ULI/%original_file_name%
