files:
  - source: Metro/localisation/english/ARB/**.yml
    translation: Metro/localisation/%language%/ARB/%original_file_name%
  - source: Metro/localisation/english/ALK/**.yml
    translation: Metro/localisation/english/ALK/**.yml
  - source: Metro/localisation/english/AVT
    translation: Metro/localisation/%language%/AVT/%original_file_name%
